# Peer Graded Assignment 1

## Loading and preprocessing the data

```{R echo=TRUE}
unzip("activity.zip")
activity <- read.csv(file = 'activity.csv')
```

## What is mean total number of steps taken per day?

Histogram of the steps taken each day

```{R echo=TRUE}
steps <- tapply(activity$steps, activity$date, sum, na.rm = TRUE)
hist(steps, col="blue", breaks=10)
```

Mean and median of the total number of steps taken per day

```{R echo=TRUE}
meansteps <- mean(steps)
meadiansteps <- median(steps)
```

The mean is `r meansteps` and the median is `r meadiansteps`

## What is the average daily activity pattern?

Average daily activity pattern

```{R echo=TRUE}
interval <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)
plot(interval, type = "l", main="Average daily activity pattern",
     xlab = "5-minute interval", ylab = "Average number of steps taken")
```

Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

```{R echo=TRUE}
asc <- interval[order(-interval)]
max <- asc[1]
```

The interval of `r names(max)` has `r max` as the maximum value.

## Imputing missing values

```{R echo=TRUE}
totalna <- sum(is.na(activity$steps))
```

The amount of missing values is `r totalna`.

Filling in all of the missing values in the dataset

```{R echo=TRUE}
medianactivity <- tapply(activity$steps, activity$interval, median, na.rm = TRUE)
newactivity <- activity
for (i in names(medianactivity)) {
    newactivity$steps <- replace(
                    newactivity$steps,
                    which(is.na(newactivity$steps)),
                    medianactivity[[i]])
}
```

Histogram of the total number of new steps taken each day

```{R echo=TRUE}
newsteps <- tapply(newactivity$steps, newactivity$date, sum)
hist(newsteps, col="red", breaks=10)
```

Mean and median of the total number of new steps taken per day

```{R echo=TRUE}
meanperday <- tapply(activity$steps, activity$date, mean)
medianperday <- tapply(activity$steps, activity$date, median)
newmeanperday <- tapply(newactivity$steps, newactivity$date, mean)
newmedianperday <- tapply(newactivity$steps, newactivity$date, median)
```

Histogram of means 

```{R echo=TRUE}
hist(meanperday, col="blue", breaks = 10)
```

```{R echo=TRUE}
hist(newmeanperday, col="red", breaks = 10)
```

The new values differ from the estimates from the first part of the report. We see an increase in the interval near zero thanks to the missing values replaced.

## Are there differences in activity patterns between weekdays and weekends?

Creating a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

```{R echo=TRUE}
newactivity$week <- "weekday"
for (i in 1:length(newactivity$steps)){
  if(weekdays(as.Date(newactivity$date[i], "%Y-%m-%d"))=="sábado" |
     weekdays(as.Date(newactivity$date[i], "%Y-%m-%d"))=="domingo"){
    newactivity$week[i] <- "weekend"
  }
}
newactivity$week <- as.factor(newactivity$week)
```

Panel plot containing a time series plot of the 5-minute interval and the average number of steps taken, averaged across all weekday days or weekend days.

```{R echo=TRUE}
library(lattice)
aggr <- aggregate(steps ~ interval + week, newactivity, mean)
xyplot(steps ~ interval | week, data = aggr, type = "l", 
       xlab = "5-minute interval", 
       ylab = "average steps taken")
```
